### ISSUE TITLE
Required OAuth credentials not provided. Make sure your API invocation call has a header: "Authorization: Bearer ACCESS_TOKEN"

### ISSUE THREAD

**Issue by trakkiesDev** [quby-energy/ToonDemoApplication#2]
Out of the box installed the API, and have it running on port `8080` following the instructions, and entered the `APIKEY`, `APISECRET`, `username` and `password`.

First error in the console after I click `login` is:

```
 api.toonapi.com/toon/api/v1/temperature/states:1 GET      https://api.toonapi.com/toon/api/v1/temperature/states 500 (Internal Server Error)
```

And I get the responseText:  `"{"code":500,"type":"Internal server error.","message":"Unable to find virtual display. Try to register the display first.","description":"Unable to find virtual display. Try to register the display first."}"`

And then continually: `GET https://api.toonapi.com/toon/api/v1/status 500 (Internal Server Error)` will show in console, it will try over and over.

And when I go to: `https://api.toonapi.com/toon/api/v1/status`, this error is shown: `Required OAuth credentials not provided. Make sure your API invocation call has a header: "Authorization: Bearer ACCESS_TOKEN"` or:

```
 <ams:fault xmlns:ams="http://wso2.org/apimanager/security">
  <script id="tinyhippos-injected"/>
   <ams:code>900902</ams:code>
   <ams:message>Missing Credentials</ams:message>
   <ams:description>
   Required OAuth credentials not provided. Make sure your API invocation call has a header:        "Authorization: Bearer ACCESS_TOKEN"
   </ams:description>
   </ams:fault>
```

While on the other side, in my `nodejs` console it says: `Received a request for a new token!` and get a `refresh_token` and `access_token` back...

So, I don't understand why this is not working, while the client side errors clearly state I don't have the right credentials, the server side does. Unless I have to login seperately on the client side, but this is not possible, since the `login` button goes on right away and doesn't ask for credentials.

I'm pretty sure this is an issue on the server side, not being able to verify my APIKEY or some other server problem. I've also requested and tested a second APIKEY, but same problem.

**Comment by JacoKoster** [comment]
Hi, thanks for describing the issues you ran into, the problem can be found with the agreements. It is possible for a user to have more than one display and you have to select one before getting data. In the example-application i (wrongly) assumed this to working out of the box.

I will add a selection-screen for the agreements, with the exception of just one agreement, it will automatically select that and continue on.

**Comment by JacoKoster** [comment]
@trakkiesDev I have created the branch issue/2/selectAgreement with a possible fix, can you check if this works for you?

**Comment by JacoKoster** [comment]
@trakkiesDev We have updated the master-branch with this update, can you check if this works for you?

**Comment by TrySpace** [comment]
Thanks, that fixed it!

**Comment by gencarnacao** [comment]
Closing after fix and confirmation.
