### ISSUE TITLE
Error getting the token

### ISSUE THREAD

**Issue by waleedsamy** [quby-energy/ToonDemoApplication#5]
I add my credential, which I got after signing up, but seem there are a problem with grant_type **but I not change It**.

```
STATUS: 400
HEADERS:{
    "content-type": "application/json",
    "activityid": "1065166093413215189752321",
    "date": "Sun, 27 Mar 2016 20:13:29 GMT",
    "server": "WSO2-PassThrough-HTTP",
    "transfer-encoding": "chunked",
    "connection": "Close"
}
Error getting the token
```

returned  error is

```
{    
      error:invalid_grant,
      error_description:Provided Authorization Grant is invalid.
}
```

So if this is not have a reason with toonapi itself, can you provide a cURL sample for `token` API?

**Comment by eugenebogaart** [comment]
Looks like the issue above!  Tried this on different platforms but (Linux and Windows), but both show the same behavior.  Not sure what is going wrong.

> node app.js
> Api started on *:3001
> Webserver started on *:8080
> Received a request for a new token!
> STATUS: 400
> HEADERS:[object Object]
> Error getting the token

**Comment by Gromata** [comment]
We're looking into an issue with e-mailaddresses that are converted wrong. Could you perhaps try to change the @-sign in the username to a dot? For instance, if you registered with 'test@test.com' you could try it with 'test.test.com'.

**Comment by eugenebogaart** [comment]
Hi Bart, Thanks for the response. Substitution of the @-sign by a Dot-sign does the trick.
